namespace:
  name: prod

service:
  port: 7111  

replicaCount: 5

resources: 
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits: 
    memory: "128Mi"
    cpu: "500m"

image:
  pullPolicy: Always  
